# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

pool:
  vmImage: windows-latest

steps:
- checkout: self
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/docs'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/docs'
    azureSubscription: 'fsdh-static-assets-service-credential'
    Destination: 'AzureBlob'
    storage: 'fsdhstaticassetstorage'
    ContainerName: 'docs' # e.g., '$web' for static website hosting